### ISSUE TITLE
Fix Cancel Confirmation Dialog

### ISSUE THREAD

**Issue by coxley** [yhatt/marp#104]
If you accidentally CTRL+W, a nice dialog box asks for confirmation like you'd expect. However, unlike other things, if you hit ESC it'll quit without saving anything.

I was burned by this deleting slides I had worked on for a couple hours.

**Comment by yhatt** [comment]
We are sorry for wasting your time.
I could not reproduce it in Windows and macOS, but it reproduce in Linux (Ubuntu).

It is fatal issue as the editor, so we would fix on next hotfix version (v0.0.9.1).

**Comment by coxley** [comment]
Thanks! I should have mentioned in the issue, this was indeed on Linux (Arch).
