### ISSUE TITLE
Best way of rendering presentation as a website online?

### ISSUE THREAD

**Issue by orschiro** [yhatt/marp#105]
What a great tool, thank you!

**One question:**

What's the best way of publishing a presentation as a rendered website online?

Maybe something like [Small Victories](http://demo.smallvictori.es/presentation-theme) that is Marp-compatible?

**Comment by lemire** [comment]
I think that marp should allow us to export to an HTML file.

**Comment by will-hart** [comment]
This is already a feature request - see #16
