### ISSUE TITLE
Image missing on PDF Export

### ISSUE THREAD

**Issue by Beomi** [yhatt/marp#108]
Hello, I've tried to export document with some images.
When I write down document with preview, it seems like works nomally.
however, when I try to export document with PDF, some images are missing at all.
you can check my .md file at [here](https://gist.github.com/Beomi/23e35e2793e0d89a0a05bb8aab64cfe2)
I hope it fixed soon :)

**Comment by yhatt** [comment]
Thanks for your reporting.
Certainly the preview is working correctly. And CSS styling for exporting PDF seems having no problem. So it is most likely to be caused by PDF renderer (Chromium).

**Comment by yhatt** [comment]
FYI: Currently you can avoid this issue by trying not to protrude image size from each slide.

**Comment by yhatt** [comment]
It has already resolved in Marp Next.
