### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sdegutis** [yhatt/marp#11]
All I did was launch the app on Mac Os Ten Point Elven dot 5ive.

Looks like some kind of race condition:

~~~
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at Error (native)
    at /Users/sdegutis/Downloads/Marp.app/Contents/Resources/app.asar/js/classes/mds_window.js:1:1282
    at new e (/Users/sdegutis/Downloads/Marp.app/Contents/Resources/app.asar/js/classes/mds_window.js:1:2911)
    at EventEmitter.<anonymous> (/Users/sdegutis/Downloads/Marp.app/Contents/Resources/app.asar/js/main.js:1:994)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
~~~

**Comment by yhatt** [comment]
@sdegutis Thanks for reporting bug.

I had tried reproducing it on a while, but I couldn't. #21 by @brandly might fix this issue. It would apply to next version.

I guess it causes while opening file from the provided error traces. I would be grateful if we could see more detailed situation for bringing the bug.

**Comment by sdegutis** [comment]
@yhatt The steps to reproduce:

1. Downoad the app for the first time ever
2. Open the app for the first time ever

It only happened once for me. I can't even reproduce it.

**Comment by yhatt** [comment]
Hmm, I can't chase this issue at the moment... 
I'll still chase if you meet this bug on next release version.

**Comment by yhatt** [comment]
Close issue. Please re-open if you will see it in v0.0.9
