### ISSUE TITLE
Emojis are missing on PDF export under OSX

### ISSUE THREAD

**Issue by davidbgk** [yhatt/marp#116]
When you insert emojis like 👍 within your markdown, once exported in PDF there is no character at all. I insert emojis the standard way using OSX with ctrl+cmd+space and it works fine in any other app. The release note of the latest version mentions https://github.com/yhatt/marp/issues/92 as an improvement but that doesn't look to be effective on my Macbook.

Is there another way to insert emojis in order to be rendered within the PDF export?

**Comment by will-hart** [comment]
See #57?

**Comment by yhatt** [comment]
@davidbgk Sure. We have already reopened #57. We cloud close this issue after you check it.

**Comment by davidbgk** [comment]
Alright, I confirm that it works with the Github/Slack notation but not with "native" Emojis.
