### ISSUE TITLE
Sync markdown Edit/Rendering window

### ISSUE THREAD

**Issue by larabih** [yhatt/marp#117]
It is possible to add the synchronisation option to Marp in objectif to sync Edit window with Render window : 
 * By scrolling the editing pane the rendering pane move with it.
 * To simplify search, like as TeXShop  _forward-inverse-search_  **`cmd + right click`**

**Comment by will-hart** [comment]
Duplicate of #24?

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. It is a duplicated issue with #24.
