### ISSUE TITLE
transparent PNG appear with a white background in default with bg image

### ISSUE THREAD

**Issue by arthurlogilab** [yhatt/marp#119]
With a BG image and an normal image with transparency on top, the background of the image is white. This is only a bug for the default theme, not gaia.

![screenshot_2016-11-08_15-10-23](https://cloud.githubusercontent.com/assets/445200/20102201/85a64310-a5c5-11e6-8140-db0e4c308795.png)
![screenshot_2016-11-08_15-10-10](https://cloud.githubusercontent.com/assets/445200/20102202/85adc892-a5c5-11e6-997d-b10d4294b56e.png)

**Comment by oschrenk** [comment]
Same issue with svg images

**Comment by Rakhmanov** [comment]
Solution for white background on images:
```
<style type="text/css">
    img {
  	    background-color: transparent!important;
    }
</style>
```

**Comment by yhatt** [comment]
[Marp Next](https://github.com/marp-team/marp)'s default theme (in [marp-team/marp-core](https://github.com/marp-team/marp-core)) has fixed this problem by overriding `background-color` style. You can already use in [CLI interface](https://github.com/marp-team/marp-cli).

https://github.com/marp-team/marp-core/blob/23d21eab1bce99338d6f2d68cd6448659a681f25/themes/default.scss#L114-L116

For current Marp, the above workaround would work.
