### ISSUE TITLE
PDF Export doesn't honor style of theme

### ISSUE THREAD

**Issue by nicholas-peterson** [yhatt/marp#12]
Reproduce:
Set theme on slides, 
`<!-- $theme: gaia -->`
`<!-- template: invert -->`

Then export to PDF. The text color is light but the background is white, so in essence it's unreadable.

**Comment by yhatt** [comment]
@nicholas-peterson Thanks for reporting bug. But I couldn't reproduce it with using markdown below.

```markdown
<!-- $theme: gaia -->
<!-- template: invert -->

Test
```

*Actually I have known very similar bug caused on previous version 0.0.7.* If you are using Marp 0.0.7's and the view mode Markdown only, theme's resources of each slide (Background, Font) were not loading and they had not applied on PDF.

I had thought causes of this were reduced, but it still brings mis-rendering...

**Comment by nicholas-peterson** [comment]
You're right, turns out I had 'Replace Document Colors' on in Acrobat Reader. No bug!

**Comment by yhatt** [comment]
Oh, I got it. I thank your useful report.
