### ISSUE TITLE
PDF generated by marp gets footer upside down on slideshare

### ISSUE THREAD

**Issue by arthurlogilab** [yhatt/marp#121]
I don't know if this is a slideshare bug or a marp bug, so I'm posting it on both sites. 

I generated the following PDF with marp : http://slides.logilab.fr/2016/meetup_monitoring_webapp.pdf which look fine.

Uploading them to slideshare.net I get the footer upside down : http://www.slideshare.net/arthurlutz/meetup-nantes-monitoring-supervision-dune-application-web-et-de-son-architecture

**Comment by scotte** [comment]
@arthurlogilab How did you even get images in the footer to begin with? I can't get either markdown or html to render as anything but raw text. If I could even just get it upside down I'd be happy. :-)

**Comment by arthurlogilab** [comment]
@scotte they are not images, this is simply text that you put in a <footnote> tag : 

```
<!-- footer: Put text here, indeed you cannot add images or html  -->
```

**Comment by scotte** [comment]
Oh, I see - the presentations linked above have what looks like graphics in the footer, and I couldn't make that work - this explains why. I guess that's a background image. Thanks for the reply.
