### ISSUE TITLE
Problem using french accents

### ISSUE THREAD

**Issue by BobPeterson** [yhatt/marp#127]
Hi, 

Thanks for your work, it seems great. I wanted to use it but I had a problem adding accents. I write in french so I had accent like "à". 

Adding this simple example: 
```
# Test
- **Mettre à jour**
```

When you save the document, you close it and open it again, you obtain: 
```
# Test
- **Mettre Ã  jour**
```

Thanks.
Have a good day !

**Comment by larabih** [comment]
Hi @BobPeterson  ,

I test to save a french document with Marp and it seems work for me.

```markdown
Marp write french ...
=========================
* àààààà
* ééééééé
* ùùùùùùù
* èèèèèèèè
* çççççççç
* êêêêeêêê
```

**Comment by cybertaf** [comment]
Hi @BobPeterson  and @larabih ,
Same for me french accents work great.

@BobPeterson  Maybe you should open file to UTF-8 encoding
i got the same "issue" if opened with Western ISO or Windows.

Have a nice day !

**Comment by lemire** [comment]
I also got this problem once, but I cannot reproduce it. I think that the problem is real, but we need a reproducible case.
