### ISSUE TITLE
Table render problems

### ISSUE THREAD

**Issue by pnizet** [yhatt/marp#128]
When rendering a pdf the upper line of the table is repeated on top of the slide :

![bug_table](https://cloud.githubusercontent.com/assets/8044949/20396113/6c0f9de4-ace5-11e6-93e6-b5ee92cee965.png)

**Comment by yarray** [comment]
Possible duplicate of #101 ?

**Comment by pnizet** [comment]
indeed. Sorry for haven't seen #101 
You can close it
