### ISSUE TITLE
BG images only with local files?

### ISSUE THREAD

**Issue by svenschaefer** [yhatt/marp#131]
This URI syntax doesn't work:
`![bg](https://unsplash.com/?photo=6liebVeAfrY)`

**Comment by pnizet** [comment]
Maybe because it is not a picture ?
Because this works
`![bg](https://images.unsplash.com/photo-1478147427282-58a87a120781?dpr=1&auto=format&fit=crop&w=1500&h=1000&q=80&cs=tinysrgb&crop=)`

(I got the url of the picture by doing a right-click on the background)

**Comment by svenschaefer** [comment]
Thx!
