### ISSUE TITLE
Support alternative syntax highlighting methods

### ISSUE THREAD

**Issue by SuperV1234** [yhatt/marp#132]
As far as I understand, Marp currently uses `highlight.js` to provide syntax highlighting. It is however not working properly with C++11 and C++14. As an example, the following code does not get highlighted correctly:

```cpp
template <typename A, typename B>
auto add(A a, B b) -> decltype(a + b)
{
    return a + b;
}
```

![incorrect highlighting](http://i.imgur.com/XnkOGPJ.png)

I think that users should be able to provide replacements for `highlight.js`, and other preinstalled options such as Pygments should be considered.

**Comment by SuperV1234** [comment]
It would also be very beneficial to invoke `highlightJs.highlight` with `ignore_illegals=true` [*(see the docs)*](http://highlightjs.readthedocs.io/en/latest/api.html), as it allows the code snippets I posted above to be correctly highlighted.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. #134 was already merged and released.
