### ISSUE TITLE
PDF Export stops at 0.0.10, but works with 0.0.9

### ISSUE THREAD

**Issue by Beomi** [yhatt/marp#136]
https://gist.github.com/Beomi/2f0439373a2d3bcb301e1d1b0908c18e

Here's my "Stopped" MD File.

I Tried to export PDF with 0.0.10 but it didn't work, stop and filled with all-white-screen.(Nothing shown)
So I've tried with 0.0.9, and it worked!
(didnt' work with 0.0.8)

Could you check it plz?

**Comment by lemire** [comment]
@Beomi  I have tested with your particular file, I can export PDF just fine with 0.0.10.
