### ISSUE TITLE
How change the background of gaia?

### ISSUE THREAD

**Issue by ISosnovik** [yhatt/marp#137]
Gaia is awesome but
- The background. How could I change it?
- Code blocks. They are so contrast. 

How to change    them?
How could I make my own theme?

**Comment by matsubara0507** [comment]
I think, quick way is that make css and write link tag to top of md file.
When writing CSS, It is better to refer to `sass/themes/gaia.sass`.
Write the link tag as follows:

```markdown
<link rel="stylesheet" href="/gaia.css">
<!-- $theme: gaia -->

# Introducing ==Gaia== theme

#### Marp's new slide theme

###### Created by [Yuki Hattori (@yhatt)](https://github.com/yhatt)

---
```

but, this way is very hard.

so, I recommend that you actually build at local.
In that case, create a sass file, put it in `sass/themes/` and rewrite the coffee file a bit.
rewrite the 32nd line of `mds_md_setting.coffee`, if make `sass/themes/hoge.sass`

```coffeescript
  return if basename in ['default', 'gaia', 'hoge'] then "css/themes/#{basename}.css" else null
```

**Comment by yhatt** [comment]
I think updating source code of the current Marp to customize theme is too hard.

In [Marp Next](https://github.com/marp-team/marp), we prepared a controlled way to customize gaia theme, that came from [Marpit framework](https://marpit.marp.app/theme-css?id=import-rule).

```
/* theme.css */
@import 'gaia';

section {
  background: white;
}
```

You can use custom theme in [CLI interface](https://github.com/marp-team/marp-cli).

```
npx @marp-team/marp-cli slide.md --theme theme.css
```

If you want not to create a new theme, [you can use an inline `<style>` tag](https://marpit.marp.app/theme-css?id=tweak-style-through-markdown).

```
---
theme: gaia
---

<style>
section {
  background: white;
}
</style>
```

Please track #5 about the support of custom CSS theme in GUI interface of Marp Next.
