### ISSUE TITLE
Features desperately needed: Dark theme, and automatic scrolling

### ISSUE THREAD

**Issue by dessalines** [yhatt/marp#138]
Nearly all online markdown editors have these.

**Comment by will-hart** [comment]
Duplicate of #117 and #24.

Dark theme do you mean for the editor or the slides? If the slides, duplicate of #115, #5 and #1

**Comment by dessalines** [comment]
Dark theme for the entire app, but primarily the editor window and the markdown view.

**Comment by Naereen** [comment]
@yhatt any update?

**Comment by yhatt** [comment]
We've splited out issues to focus one topic per issue. Refer to #245 about dark theme.

As he already pointed out above, the other topics are duplicated issues.

**Comment by Naereen** [comment]
OK!
