### ISSUE TITLE
[Feature] Search functionality

### ISSUE THREAD

**Issue by grubersjoe** [yhatt/marp#141]
I would be great if you could search the buffer with a shortcut like `ctrl + f`. I'm intuitively trying to do it all the time. This would be very useful to navigate in large slide sets.

**Comment by Namek** [comment]
It was easy to add:
https://github.com/Namek/marp/commit/60f3d5b42f65175150b68f2fed6a49c48ca802e3

**Comment by tzok** [comment]
Can you issue a PR for these commits? I would like to see this functionality in Marp.
