### ISSUE TITLE
Export as PDF remember last filename

### ISSUE THREAD

**Issue by noisygecko** [yhatt/marp#142]
It would be great if the "Export Slides as PDF..." option would remember the last filename used so I don't have to select it and then click save.  It seems to remember the directory, but not the filename.

I would actually love it if there was a way to have it automatically export when I save, or have a single click button to do that.

**Comment by Naereen** [comment]
Hi,
I agree, this feature is needed.

@yhatt would it be hard to do?

**Comment by DSLituiev** [comment]
IMO, it should suggest the name of the PDF as the basename of Markdown file, i.e. `basename.md -> basename.pdf` instead of `Untitled.pdf`

**Comment by valentinsteinwandter** [comment]
Hi, I implemented the feature and send the pull request to the core developer.

**Comment by Naereen** [comment]
Based on the observation that some PR have been opened since last August, I am not so optimistic about that. But thanks for trying!

@yhatt Do you still have time to maintain the project?

**Comment by valentinsteinwandter** [comment]
Let's hope that @yhatt has still time. I really like this project. Otherwise we have to fork it.

**Comment by Naereen** [comment]
Sure, we could. I like it too, but don't really have the time, and I am certainly not an Electron expert.

**Comment by valentinsteinwandter** [comment]
Me neither, but the author seem to be really active on his other projects so probably there is some chance he will continue here as well.

**Comment by will-hart** [comment]
https://github.com/yhatt/marp/wiki

> NOTICE!
>
> Marp 0.0.x has already dropped maintenance. Currently I'm rewriting Marp with using much better technologies:

**Comment by valentinsteinwandter** [comment]
@will-hart thanks for the link!

Wouldn't it make sense to don't totally stop the development of 0.0.x as long as no new version is foreseeable? I mean it doesn't look like we will get Marp 1.x anytime soon. What do you think?

**Comment by Naereen** [comment]
@yhatt for 6172e4a and latest release [v0.0.11](https://github.com/yhatt/marp/releases/tag/v0.0.11) : is the update to next release (on the github.io website) automatic?

**Comment by Naereen** [comment]
I just tested the latest release, it does suggest to use the .md filename as the .pdf default filename, but does *not* remember the last choice.
