### ISSUE TITLE
Heading top

### ISSUE THREAD

**Issue by roydekleijn** [yhatt/marp#143]
Hi,

How to position the heading/title on the top of every page ??

Also, is there a way to set the color of #  or ##  lines?

Thanks,
Roy

**Comment by Naereen** [comment]
Hi,
No, not that I know of, Marp does support this yet.

@yhatt would it be hard to do? (if you show me the file to edit, I will try to figure it out)

**Comment by fabriciofx** [comment]
@yhatt Any news about this feature?

**Comment by cdqwertz** [comment]
To set the position of the heading to the top of the page you need to change the default theme.

**Note: You need to run Marp from source or rebuild Marp for this to work.**

1. Go to this file: /path/to/the/marp/source/code/sass/themes/default.sass (https://github.com/yhatt/marp/blob/master/sass/themes/default.sass)
2. Remove line 10
3. Add the following code one line after the line you just deleted:
```sass
  .slide_inner
    margin-top: 100px
```

**Comment by yhatt** [comment]
Yep, and Marp Next (#267) can be easy to create theme and tweak style.

See also: https://github.com/marp-team/marpit/issues/153#issuecomment-481252049
