### ISSUE TITLE
Color of page number

### ISSUE THREAD

**Issue by Qlaize** [yhatt/marp#144]
Hi,
I activate the page numbers with directive `<!-- page_number: true -->`
Is it possible to change the color of page numbers with this directive ?

Thanks.

**Comment by Naereen** [comment]
I think it is not implemented, yet. But it should be possible.

@yhatt would it be hard to do? (if you show me the file to edit, I will figure it out)

**Comment by yhatt** [comment]
This is a workaround for current Marp.

```markdown
<!-- page_number: true -->

<style>
.slide_page {
  color: red !important;
}
</style>
```

[Styling page number is supported officially](https://marpit.marp.app/theme-css?id=pagination) in [Marp Next](https://github.com/marp-team/marp). It will work in future version:

```markdown
---
paginate: true
---

<style>
section::after {
  color: red;
}
</style>
```
