### ISSUE TITLE
Improve support for LaTeX/KaTeX in the Markdown editor: no markup inside math blocks

### ISSUE THREAD

**Issue by Naereen** [yhatt/marp#149]
Hi,
First, :clap: because Marp is awesome. Thanks for this neat software!

Second, I was wondering if it could be possible to improve the support for LaTeX in the editor, specially the way it parses Markdown special characters inside `$ ... $` or `$$ ... $$` or `\( ... \)` or `\[ ... \]` (LaTeX math blocks).

Basically, LaTeX can use `*`, `_` and every possible Markdown syntax inside a math block, but it should *not* be understood as Markdown markup if it's inside a math block. For instance, `$ **x** $` should not show `x` in bold in the editor pane.

## Example
For instance, the following Markdown code:
```markdown
- Example of math using an underscore: $a_i \in \mathcal{A}_i$
- Now the rest of the text is highlighted in italic, as this $y_j$ underscore was understood as "start italic"...
- And only this will close the underscore $a_i \in \mathcal{A}_i$ underscore was understood as "start italic"...
```
In GitHub, this issue is not present:
- Example of math using an underscore: $a_i \in \mathcal{A}_i$
- Now the rest of the text is highlighted in italic, as this $y_j$ underscore was understood as "start italic"...
- And only this will close the underscore $a_i \in \mathcal{A}_i$ underscore was understood as "start italic"...

But in Marp, it is:
![example bug marp](https://cloud.githubusercontent.com/assets/11994719/22694892/34131a66-ed49-11e6-8ee6-eeba901c36ce.png)

----

I don't know if you could use the same Markdown editor as the one used in [typora](https://github.com/typora/), but their software is also built with electron, and does not have this bug.

> Thanks in advance.

**Comment by will-hart** [comment]
The editor is [CodeMirror](https://github.com/codemirror/CodeMirror), probably best to file an issue over there.

**Comment by Naereen** [comment]
OK, that's done. Could I ask you to also follow this bug on CodeMirror, and if it is resolved, try to rebuild Marp with the latest version?
Thanks :+1: !

**Comment by Naereen** [comment]
Sadly, [they seem to not consider this as bug](https://github.com/codemirror/CodeMirror/issues/4555#event-955305408), and so no solution will come from CodeMirror's maintainers.

Any chance of fixing this inside Marp, on top of CodeMirror `gfm` mode?
