### ISSUE TITLE
Hope  Marp support process flow chart <based on markdown grammar>

### ISSUE THREAD

**Issue by renxiangbin** [yhatt/marp#150]
if  Marp support process flow chart <based on markdown grammar>....

We are looking forward to using it ! 

Thanks

**Comment by yhatt** [comment]
In [the core](https://github.com/marp-team/marp-core) of [Marp Next](https://github.com/marp-team/marp), we are considering to support flowchart rendering by [mermaid.js](https://mermaidjs.github.io/). Please track #125.
