### ISSUE TITLE
feat: Marp watches file and update if it's changed

### ISSUE THREAD

**Issue by benjycui** [yhatt/marp#151]
Use case:

1. I open Marp and my favorite editor.
1. Edit in my editor
1. Marp will update its preview.

**Comment by LitoMore** [comment]
I have the same problem.

I opened Marp and MacDown.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. This issue is duplicated of #25.

And we have released CLI tools that has supported watch mode in [Marp Next](https://github.com/marp-team/marp). See https://github.com/yhatt/marp/issues/25#issuecomment-427670640.
