### ISSUE TITLE
Katex environment does not work 

### ISSUE THREAD

**Issue by chengmingbo** [yhatt/marp#159]
I have tried several KaTex environment parameters such as matrix bmatrix aligned. Marp does not work.
My platform: Mac OS X EI Capitan 10.11.6
<img width="827" alt="marp_issue" src="https://cloud.githubusercontent.com/assets/1748282/23338107/6b34feae-fc3c-11e6-88c0-01e656ce654b.png">

**Comment by will-hart** [comment]
Did you forget to wrap it in `$$`? 

![image](https://cloud.githubusercontent.com/assets/391950/23343913/7f3807a8-fcc7-11e6-8179-034603c843a2.png)
