### ISSUE TITLE
Emojis not working when generating PDF

### ISSUE THREAD

**Issue by pedronaresi** [yhatt/marp#165]
I saved as PDF and the "emojis" did not showed off.

**Comment by kohashi** [comment]
See #57
You need use syntax like `:+1:`.

**Comment by Kelym** [comment]
I used to have the same problem when I used &#9556; to key in emojis. Switching to :beer: and export works!

**Comment by yhatt** [comment]
We're making a clean sweep of duplicated issues. Our workings about this issue have reported in https://github.com/yhatt/marp/issues/57#issuecomment-427677788.
