### ISSUE TITLE
Find and Find-Replace functionality

### ISSUE THREAD

**Issue by DSLituiev** [yhatt/marp#168]
Find and Find-Replace functionality would be much appreciated.

**Comment by Namek** [comment]
Especially `Find` - I use it to jump throughout text.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. It is a duplicated issue with #141.

Currently we are not focused to editor improvement because have to improve the base to make slides and editor improvment is triggered scope creep.
