### ISSUE TITLE
How to play after writing

### ISSUE THREAD

**Issue by shimachao** [yhatt/marp#169]
eg. how to play the example.md ? just a writer?

**Comment by will-hart** [comment]
Usually export to PDF and use the PDF to present. See #13

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. Marp is just a writer. In the current Marp, you should use exported PDF.

In [Marp Next](https://github.com/marp-team/marp), [a new CLI interface](https://github.com/marp-team/marp-cli) can export HTML that is ready to play in browser.

```
npx @marp-team/marp-cli slide.md -o output.html
```

Please refer to [yhatt/marp-cli-example](https://github.com/yhatt/marp-cli-example): https://cranky-colden-877afa.netlify.com/
