### ISSUE TITLE
pdf export in document mode

### ISSUE THREAD

**Issue by setop** [yhatt/marp#170]
I use Marp as a markdown editor for both slidesets and documents and I enjoy it !

When editing a document, I use "Markdown" view instead of "Slide" view.
And the document has no slide separator (---).

I'd like to export a document as a pdf (CTRL+Shift+E). But currently, it produces only one slide with a small visible part of the document. Plus I'd like font size to be smaller for document than for slideset.

**Comment by Smiley32** [comment]
Same for me 👍

**Comment by valentinsteinwandter** [comment]
Yes I love the style of the documents and it would be great to be able to export that as PDF.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. This issue is duplicated of #4.
