### ISSUE TITLE
Transparency in Images

### ISSUE THREAD

**Issue by peter-ki** [yhatt/marp#171]
PNG's get a white background so transparency in it is not transparent. If you use images in slides with a background, this can be disturbing.

**Comment by hholst80** [comment]
What do you mean? You probably have rendered your PNGs with a white background instead of a transparent background?

**Comment by Rakhmanov** [comment]
Duplicate of #119

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. https://github.com/yhatt/marp/issues/119#issuecomment-409743232 has a workaround for current Marp.
