### ISSUE TITLE
How to change the size of picture?

### ISSUE THREAD

**Issue by superPershing** [yhatt/marp#173]
How can I change the size of picture? Many times I want to change the size of picture, But I don't know where to make change to configurations.

**Comment by larabih** [comment]
Personally, I use this syntax:
`
<img src="pathToPicture.png" style="width: 50%" align="left"/>
`

and it works well.

**Comment by superPershing** [comment]
@larabih Thank you! But I want to set picture's size more than 100%, such as 120% or bigger. But it seem to limit the picture's size no more than 100%.

**Comment by matoken** [comment]
I use this syntax:

```
![50%](pathToPicture.png)
![120%](pathToPicture.png)
```

and background image to.

```
![bg 200%](pathToPicture.png)
```

It will be larger than 100%, but the image size to be limited by the slide size. Please try with a small image.
The background image got bigger.

**Comment by superPershing** [comment]
@matoken Thank you! I try to change the percentage of the picture size, while the number is more than 70%, my picture cannot be larger. While I put my picture in Powerpoint slides, its size is larger than in marp when I using the origin size. I hope marp can set the picture' size that ignore the slide size.

**Comment by connorshea** [comment]
@matoken this is awesome, it should definitely be in the docs :)

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. In [Marp Next](https://github.com/marp-team/marp), we have documented about image resizing syntax in [the docs of Marpit](https://marpit.marp.app/image-syntax), that is a base framework of [marp-core](https://github.com/marp-team/marp-core).
