### ISSUE TITLE
Marp 1.0.0 and current version

### ISSUE THREAD

**Issue by valentinsteinwandter** [yhatt/marp#174]
It seems that the active development of this Marp version stopped somewhere in summer 2016. No pull requests were accepted since there and it seems that the main contributer does not want to provide any updates for Marp 0.x.

There is an entry in the [Marp wiki](https://github.com/yhatt/marp/wiki/Roadmap-to-Marp-1.0.0) about the roadmap to version 1.0.0 which looks quiet impressive. However, there is neither public code to find somewhere no any more information about the progress of Marp 1.0. 

Does anyone have any idea when we'll get the first "pre-release" of Marp 1.0 and if the main contributer is still working on that?

**Comment by livc** [comment]
What a pity.

**Comment by mindplay-dk** [comment]
That really is a shame.

Hm, I've been poking through the codebase - it's really not that much code, so I'm thinking about:

1. Porting it to TypeScript - I find that CoffeeScript is really difficult to navigate, even a small codebase like this.

2. Make it run in the browser - the process of building from sources to a binary application is a clumsy extra step that slows down development.

Is there any practical reason this needs to be a desktop application?

The only application-feature it seems to have is PDF export, but there would be ways around that.

Loading and saving files? Meh, let's make it read/write gists on Github instead.

I think once the codebase is browser-based and modern ES6, and we remove the clunky build-step and make it easier to iterate on the code, it'll be easier and faster for most people to work with - maybe then more people will be interested in collaborating further on this?

**Comment by xgouchet** [comment]
AFAIAC, I often work during my commute, and this usually means without internet connection. And even when then I'm not committing, I'm often working in offline context, so a desktop a fixation bas a lot of value for me as it let's me work even without a access to the internet.

**Comment by oleteacher** [comment]
Use MARP in classroom environment with younger kids and their stations are not allowed internet access. If could not load and save files locally, would not be able to use MARP...

**Comment by valentinsteinwandter** [comment]
I agree with @xgouchet and @oleteacher. I need desktop functionality as well.

**Comment by SuperV1234** [comment]
Note that @yhatt is actively working on
https://github.com/yhatt/markdown-it-incremental-dom

AFAICS that's going to be a core component of the next release of Marp.

**Comment by mindplay-dk** [comment]
> I need desktop functionality as well.

[offline-first](https://github.com/pazguille/offline-first) then, hmm?

**Comment by yhatt** [comment]
Now we are following https://github.com/yhatt/marp/issues/174#issuecomment-294577169. Marp Next is developing by TypeScript (except Marpit) and the main interface will become Marp Web. The future of desktop version would just be wrapping Web interface.

I had the suspicious look for TypeScript and PWA 2 years ago, but now I'm betting to them. If you still have a worry to offline usage, try [Marp Web (demo)](https://web.marp.app). It can use offline after the first access.

Appendix: markdown-it-incremental-dom was a training of JS package for mine. Now I have decided changing the policy to use more grown VDOM like React or Vue.
