### ISSUE TITLE
Need support for variables/macros in marp

### ISSUE THREAD

**Issue by csj-github** [yhatt/marp#179]
Today I use the footer on each slide as the "Presentation Title".

This requires to explicitly define the footer separately. Tomorrow if we change the Presentation Title, I will need to update the Footer separately. It should be possible to define a variable with a "text string" and use it as text content with in the presentation

Example:
```
<!-- Comment: First Slide --->
<var1>This is the title for my presentation!</var1>
# $var1$

---
<!-- Comment: Second Slide --->
<!-- Footer: $var1$ -->

----
```

**Comment by SuperV1234** [comment]
@csj-github: I implemented Javascript slide metaprogramming [in my fork](https://github.com/SuperV1234/marp) by literally calling `eval(...)`  on the Markdown source, adding some syntactic sugar for injection. Here's an example:

![example](https://pbs.twimg.com/media/DLo1KVzX4AAcsL7.jpg:large)

PRs welcome.
