### ISSUE TITLE
Html style tag breaks current styling

### ISSUE THREAD

**Issue by nournia** [yhatt/marp#18]
Hi,
Adding an empty `<style></style>` tag to first line of Gaia theme example breaks center aligned tags.

I think adding html styles is a very important part of customizing presentations and it should be a first-class feature.

**Comment by yhatt** [comment]
Thanks for your reporting.

I know the clearly cause bringing it. A centering of Gaia theme is applied to slide had only headings tag `h1`-`h6` or quote tag `blockquote`.

I'm going to fix to ignore invisible tag for centering.

**Comment by yhatt** [comment]
@nournia We fixed this issue in PR #40. It will apply in next version v0.0.9. Thanks for reporting this issue!

![](https://cloud.githubusercontent.com/assets/3993388/16945005/32bd5b32-4dde-11e6-8a4a-3c3fd901f820.png)

**Comment by nournia** [comment]
Thansk.
