### ISSUE TITLE
Feature Request: mbox environment in math mode

### ISSUE THREAD

**Issue by y-takashina** [yhatt/marp#181]
The mbox environment is not available in math mode. I think introducing \mbox environment helps non-English writers create more reader-friendly slides for their audience.

Example: 
```
$$
\ln\frac{p(x|y=\mbox{異常})}{p(x|y=\mbox{正常})}
$$
```

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. `\mbox` is not supported in KaTeX. (https://katex.org/docs/support_table.html#m)

Essentially this is an issue of [KaTeX](https://github.com/Khan/KaTeX), not Marp. It's better to report to [KaTeX issue tracker](https://github.com/Khan/KaTeX/issues).
