### ISSUE TITLE
another competitor

### ISSUE THREAD

**Issue by alperyilmaz** [yhatt/marp#185]
This is not an issue *per se*, just a wish..

MacOS already had a nice software, [DeckSet](https://www.decksetapp.com/),  which can make beautiful presentations from markdown files. Its output is actually very impressive. 
Now,  there's another fine MacOS app called [Slidium](https://www.neomobili.com/products/slidium-markdown-presentation/). You can add data, columns, etc.. Amazing..
Hopefully Marp becomes as good as them in near future..

**Comment by hholst80** [comment]
Too bad its only a Mac app thus fairly useless for us on Linux or Windows.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. We have to focus our task about Marp (and Next) at GitHub issue tracker. But your wish is as same as ours!
