### ISSUE TITLE
[Feature request] Add Marp to Chocolatey registry

### ISSUE THREAD

**Issue by dimkir** [yhatt/marp#190]
Software packagers allow conveniently install **and update** software on machines. (Think `apt-get`  on Debian/Ubuntu). 

For Windows it's https://chocolatey.org/  

It would be great to add Marp to Chocolatey registry, which would allow to install it on windows machine via:

    choco install marp

or upgrade via

    choco update marp

Going into the future, even though installation of Marp is kinda simple, one-liner upgrade, I believe, would add add a lot of extra value. (eg. requirement to upgrade to v0.11).

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. It is a duplicated issue with #6.

In future, Marp will become to be a web-based tool ([marp-web](https://github.com/marp-team/marp-web) on [Marp Next](https://github.com/marp-team/marp)). After it was released, we will consider about desktop app...
