### ISSUE TITLE
Scrollbar shows up when code exceeds screen size

### ISSUE THREAD

**Issue by akaz00** [yhatt/marp#192]
Hi,

whenever after adding code block(using triple backtick(`)) and write long one line of code,

I see scrollbar below code section. (It is really painful when adding long one line of comment to explain code)

is there way to hide scrollbar by automatically adding new line before code exceeds screen size?

thanks.

**Comment by yhatt** [comment]
In [the core](https://github.com/marp-team/marp-core) of [Marp Next](https://github.com/marp-team/marp), we have supported auto scaling of code block in several themes (marp-team/marp-core#23). This behavior also has a compatibillity with the other app. (e.g. Deckset)

|[Before](https://github.com/marp-team/marp-core/files/2321876/auto-scale-before.pdf)|[After](https://github.com/marp-team/marp-core/files/2321877/auto-scale-after.pdf)|
|:---:|:---:|
|![auto-scale-before](https://user-images.githubusercontent.com/3993388/44632583-3ac70c00-a9b8-11e8-9653-626bcb285be3.png)|![auto-scale-after](https://user-images.githubusercontent.com/3993388/44632584-3ef32980-a9b8-11e8-919a-85237a21569a.png)|

[A new CLI interface](https://github.com/marp-team/marp-cli) can try this behavior.
