### ISSUE TITLE
Can I write on left/right side of an inserted image?

### ISSUE THREAD

**Issue by hcuny** [yhatt/marp#193]

**Comment by yytdfc** [comment]
you can write like this:
``` markdown
<img src="https://github.com/yhatt/marp/raw/master/images/marp.png" align=right width=90>
Markdown presentation writer, powered by Electron.
Markdown presentation writer, powered by Electron.
Markdown presentation writer, powered by Electron.
Markdown presentation writer, powered by Electron.
Markdown presentation writer, powered by Electron. 
```
<img src="https://github.com/yhatt/marp/raw/master/images/marp.png" align=right width=90>
Markdown presentation writer, powered by Electron.
Markdown presentation writer, powered by Electron.
Markdown presentation writer, powered by Electron.
Markdown presentation writer, powered by Electron.
Markdown presentation writer, powered by Electron.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues...
