### ISSUE TITLE
Feature Request: Footnotes

### ISSUE THREAD

**Issue by kerim** [yhatt/marp#2]
Would like to see support for Markdown Footnotes (as used on Wordpress and elsewhere, I believe based on Mulitmarkdown?). Something like this:

`Clicking this number[^fn-sample_footnote] will lead you to a footnote.

[^fn-sample_footnote]: Handy! Now click the return link to go back.`

**Comment by yhatt** [comment]
Marp's Markdown is based on [GFM](https://guides.github.com/features/mastering-markdown/) and it seems not define footnote syntax. But Marp's Markdown parser ([markdown-it](https://github.com/markdown-it/markdown-it)) can add footnote by [markdown-it-footnote](https://github.com/markdown-it/markdown-it-footnote). I'm going to try to add it soon.

**Comment by yhatt** [comment]
Hmm, I had tried to add footnote syntax by [markdown-it-footnote](https://github.com/markdown-it/markdown-it-footnote), and it worked good in markdown view. However, I have to make a few tricks to add footnotes to per slides with each of live slides preview and PDF. Give me more time!
(The common footnotes are "only" at the end of document in markdown for writing, but they would see at each of the referenced pages in slide views)

**Comment by kerim** [comment]
I understand. That does sound complicated. I hope you can figure it out!
Thanks for the explanation.

Cheers,

Kerim

On Mon, Jul 4, 2016 at 5:53 PM, Yuki Hattori <notifications@github.com>
wrote:

> Hmm, I had tried to add footnote syntax by markdown-it-footnote
> <https://github.com/markdown-it/markdown-it-footnote>, and it worked good
> in markdown view. However, I have to make a few tricks to add footnotes to
> per slides with each of live slides preview and PDF. Give me more time!
> (The common footnotes are "only" at the end of document in markdown for
> writing, but they would see at each of the referenced pages in slide views)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yhatt/marp/issues/2#issuecomment-230278502>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AADqSFlm_mS9Rtf4ZS1FIlVfBEKVuPSqks5qSPs0gaJpZM4I9htb>
> .
>



-- 

*P. Kerim Friedman 傅可恩 <http://kerim.oxus.net/>*

Associate Professor
The Department of Ethnic Relations and Cultures
College of Indigenous Studies
National DongHwa University, TAIWAN
副教授國立東華大學族群關係與文化學系

**Comment by Naereen** [comment]
Hi,
:+1: for this feature.

@yhatt any update?
