### ISSUE TITLE
There's a fork of Marp with presentation mode and speaker notes available (and JS slide metaprogramming!)

### ISSUE THREAD

**Issue by SuperV1234** [yhatt/marp#200]
*(This is not a real issue, but it might help people looking for these features.)*

I love Marp and I think it's the best tool to create technical presentations. I was fed up with the lack of:

* Presentation mode

* Speaker notes

* Macros

So I created my own fork which provides all the aforementioned features. You can find it here: https://github.com/SuperV1234/marp

Hopefully this will be good enough until Marp 1.0.0 is released. 

Some more information in this article on my webpage: https://github.com/SuperV1234/marp/commits?author=long-long-float

---

![screenshot from 2017-10-22 17-26-38](https://user-images.githubusercontent.com/918661/31864029-95becad8-b74e-11e7-9526-753de3a0c18e.png)

![screenshot from 2017-10-09 18-10-01](https://user-images.githubusercontent.com/918661/31864031-a03f674c-b74e-11e7-8626-dcb1bc97d61c.png)

**Comment by m55c55** [comment]
Sounds great! Are there any build available for that yet?

**Comment by SuperV1234** [comment]
@m55c55: nope, I don't plan on releasing any build unfortunately. Building it yourself should be quite simple - you just need `npm`.

```bash
git clone https://github.com/SuperV1234/marp
cd marp
npm build
npm start
```

**Comment by kumo** [comment]
It looks very useful, but I have had problems with theme templates, for example the Gaia theme example doesn't appear the same in Marp and my build of your fork.

**Comment by SuperV1234** [comment]
@kumo: I might have modified Gaia's `.css` file or made some other mistake. In what way does it appear different?

**Comment by kumo** [comment]
@SuperV1234 if there is a single slide then the gaia template (blue background) appears, but if I add a second slide then the first slide has the default template instead. Also, if I change templates inside a document (like the Gaia theme example) then it seems like the last theme is remembered and if I move back through the slides, they show the last theme rather than the appropriate theme for that slide.

The same also happens with the page number. In the Gaia theme example, every page except for the first and the last are page 18, whereas the first page has no number, the last page is page 19. Also the second page shouldn't even have a number since in the theme example, page numbering starts at page 3.

![Fork version](https://user-images.githubusercontent.com/7925/31969082-ae7ae19e-b913-11e7-951c-d920a642618e.jpg)
![Marp version](https://user-images.githubusercontent.com/7925/31969087-b2e26540-b913-11e7-9de5-e589037a04db.jpg)

**Comment by SuperV1234** [comment]
@kumo: thanks for the detailed report. I think everything got fixed in https://github.com/SuperV1234/marp/commit/ed67ba522193234767c8aca994fb4ec8eeae7993

**Comment by kumo** [comment]
@SuperV1234 it seems to be working properly now.

**Comment by fredtempez** [comment]
Sorry but I can wait to test your code, installed git and npm but get a lot of errors.
Could you deliver a win and deb binary ?

**Comment by fredtempez** [comment]
Up ??

**Comment by oleteacher** [comment]
This fork sounds just like what I need for classroom project.

I have built and testing but for life of me cannot figure out how to use this window:

![image](https://user-images.githubusercontent.com/26278259/33519073-20693b74-d765-11e7-80b2-d247a32b0598.png)

Sure I will be embarrassed how simple but could you give me some pointers?

Thank you!

**Comment by fredtempez** [comment]
You are right,
I did installed all the stuff needed, gulp and so on. And I got 2 stupid windows, one ´s like yours. 

Binaries needed thanks a lot ;)

**Comment by SuperV1234** [comment]
@fredtempez: sorry, I will not provide binaries. 
@oleteacher: the second window is for speaker notes. In a slide, add `<!--# hello! -->` and it will appear in the second window

**Comment by oleteacher** [comment]
> @oleteacher: the second window is for speaker notes. In a slide, add  and it will appear in the second window

Thank you! Knew it would bee simple or something I overlooked.

**Comment by fredtempez** [comment]
Could you give us all the step we need to make a complete start ? thanks

**Comment by oleteacher** [comment]
@fredtempez Working fine for me. I downloaded this forked version, unzipped and using GIT Bash simply:

npm install
npm start

Then after few tweaks and testing, finalized by:

gulp release

You should then have your builds (win exe for 32 and 64bit) and linux in a folder releases.

Only issue I had was understanding how to use the speaker note.

**Comment by hholst80** [comment]
It would be nice if you made two PRs from these changes. The meta programming I have no use for but the presentation mode sounds pretty good. :-)

**Comment by SuperV1234** [comment]
@hholst80: well, you can just not use it :) 
It is not invasive.
