### ISSUE TITLE
Not an issue, how I change the default theme...

### ISSUE THREAD

**Issue by fredtempez** [yhatt/marp#204]
[..using CSS  for beginners...](http://tic-et-net.org/2017/11/30/how-to-change-the-theme-in-marp/)

**Comment by alehandrof** [comment]
Nice idea. It kind of works, but this suggested CSS doesn't make the background black.

```
.slide {
  background-color: black;
}
```

**Comment by fredtempez** [comment]
Sure or you have to overwrite with !important

**Comment by alehandrof** [comment]
Never mind. It works just fine. I did something daft on my end 🙄

**Comment by akakeronos** [comment]
Hi,
Using 



doesn't seem to work. 

Do I have to do anything else to modify the defualt theme ? Thanks

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. We have to focus our task about Marp (and Next) at GitHub issue tracker.

In [Marp Next](https://github.com/marp-team/marp), we'll make a support custom CSS. See and track #5 (comment).
