### ISSUE TITLE
Exporting to PDF misses images

### ISSUE THREAD

**Issue by wzhliang** [yhatt/marp#205]
I have a slide that includes a single image with

    ![](image url)

with preview it's OK but when exporting to PDF that slides is empty.

Version: marp 0.0.11 on macOS

**Comment by tjohnston-cd** [comment]
I ran into this today as well. For me, the image shows up in the PDF if I resize it so that it fits on the page (e.g. use `[20%]` or whatever size works). Using it as the background with `[bg]` also allows it to show up in the PDF.

Hopefully there's a better way..

**Comment by yhatt** [comment]
Please starting to use Marp Next apps, not unmaintained Marp app. It would render slides correctly even if image has stucked out from slide. :point_right: yhatt/marp#267
