### ISSUE TITLE
How can we change font size ??

### ISSUE THREAD

**Issue by AshhChika** [yhatt/marp#208]

**Comment by AshhChika** [comment]
I would like to change font size of whole text.

**Comment by leej35** [comment]
You can change the part of text where you want to shrink or enlarge with this:
```
<span style="font-size:80%">text you want</span>
```

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. <img src="https://pbs.twimg.com/media/CR5GkCJVEAAiXNm.jpg" width="18" height="18" />
