### ISSUE TITLE
Images are not reloaded when changed on disk

### ISSUE THREAD

**Issue by hholst80** [yhatt/marp#210]
![100%](/path/to/image.png)

The image is not readed as image.png is changed on disk. Even if I modify the line above the image preview is not updated.

**Comment by bitterjug** [comment]
I'd expect to be able to re-load the images by typing Control-R in Marp but that's not implemented either.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. This issue is duplicated of #56.
