### ISSUE TITLE
long math formula out of border

### ISSUE THREAD

**Issue by livc** [yhatt/marp#212]
$
p(t)=q(\mathrm{S}\rightarrow \mathrm{NP\;\;VP})\times 
q(\mathrm{NP}\rightarrow \mathrm{DT\;\;NN})\times q(\mathrm{DT}\rightarrow \mathrm{the})  \times q(\mathrm{NN}\rightarrow \mathrm{dog})\times q(\mathrm{VP}\rightarrow \mathrm{Vi})\times q(\mathrm{Vi}\rightarrow \mathrm{sleeps}) 
$

<img width="914" alt="screen shot" src="https://user-images.githubusercontent.com/11692045/35793387-66f0e9b6-0a8c-11e8-82e5-9ed7566c09ba.png">

**Comment by yhatt** [comment]
It have supported in the next Marp at [@marp-team/marp-core](https://github.com/marp-team/marp-core#math-block).
