### ISSUE TITLE
Installation from AUR contains no SASS folder

### ISSUE THREAD

**Issue by Jakob-S** [yhatt/marp#213]
The Marp installation from AUR (Arch User Repository) doesn't seem to contain any SASS or theme Folder.
`sudo find / -type d -name "sass"` results:
`/home/jakob/Programme/franz/node_modules/node-sass/src/libsass/include/sass
/home/jakob/Programme/franz/node_modules/node-sass/test/fixtures/input-directory/sass
find: ‘/run/user/1000/doc’: Keine Berechtigung
find: ‘/run/user/1000/gvfs’: Keine Berechtigung` (it's just german)

Also the theme files gaia.sass and default.sass could not be found:
`sudo find / -name "*.sass"` results:
`/home/jakob/Programme/franz/node_modules/node-sass/test/fixtures/indent/index.sass
/home/jakob/Programme/franz/node_modules/node-sass/test/fixtures/watching/index.sass
/home/jakob/Programme/franz/node_modules/node-sass/test/fixtures/watching/bar.sass
find: ‘/run/user/1000/doc’: Keine Berechtigung
find: ‘/run/user/1000/gvfs’: Keine Berechtigung`

I also couldn't find any application folder including the themes:
`sudo find / -type d -iname "marp"` results:
`/home/jakob/.config/Marp
/usr/share/licenses/marp
/usr/lib/marp`
While listing content of listed directories:
`IDEA-PC% ls /home/jakob/.config/Marp                 
Cache  config.json  Cookies  Cookies-journal  GPUCache
IDEA-PC% ls /usr/share/licenses/marp 
LICENSE
IDEA-PC% ls /usr/lib/marp 
blink_image_resources_200_percent.pak, icudtl.dat, LICENSES.chromium.html, natives_blob.bin, ui_resources_200_percent.pak, content_resources_200_percent.pak, libffmpeg.so, locales, resources, version, content_shell.pak, libnode.so, Marp, snapshot_blob.bin, views_resources_200_percent.pak`
As you can see, there is no theme folder and non of the folders contain any relevant file.

I'm searching for the theme folder, cause I want to change some things at the Gaia theme, or add some themes.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. There are not source code in released package. You have to clone from Git.

We recognize that customizing CSS is too hard for user. In [Marp Next](https://github.com/marp-team/marp), we'll make a support custom CSS. See and track https://github.com/yhatt/marp/issues/5#issuecomment-423177213.
