### ISSUE TITLE
Export to PDF is low quality

### ISSUE THREAD

**Issue by phylodojo** [yhatt/marp#217]
I like using MARP for its simplicity, but when I went to export slides to PDF the quality is very low compared to what I see in preview. The text and images are very pixelated. Any idea how to improve the quality of the export?

**Comment by maxuewei2** [comment]
Same problem. It seems that it export every slide as an image in low quality.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. The solution is to remove `<!-- prerender: true -->` directive.

To avoid confusing, we would remove the support of `prerender` directive in Marp Next.
