### ISSUE TITLE
Presentation mode with support of wide screen

### ISSUE THREAD

**Issue by gsemet** [yhatt/marp#218]
A simple presentation mode with wide screen support (most projectors or screens are now a bit wider than 4/3) would be very helpful !

Thanks for this nice software!

**Comment by maikmerten** [comment]
I would appreciate a presentation mode as well. The main reason for me to present directly with marp would be the ability to have slides with HTML/JavaScript-fluff and e.g. animated GIFs etc. - such things break when exporting to PDF, but work fine in marp preview.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. It is a duplicated issue with #13.
