### ISSUE TITLE
Characters are changed when re open file

### ISSUE THREAD

**Issue by dabroder** [yhatt/marp#22]
I write and save:
Diseño de aplicación.

When open I see:
Dise帽o de aplicaci贸n.

**Comment by dabroder** [comment]
Probably is 'jschardet' library bug

**Comment by afiller** [comment]
Wouldn't it in general be easier to assume the file is UTF-8 (backwards compatible with ASCII) and use the UTF-8 encoding directly in the fs command?

`fs.readFile(p, 'utf8', function (err, data) {...`

UTF-8 support all "relevant" characters and also writing should be no problem then.

**Comment by dabroder** [comment]
Hello @yhatt, most editors encode `.md` in utf-8 by default, and offers options for reopen with encoding.

**Comment by yhatt** [comment]
@dabroder Thank your notification. I understood what is happening. (When opening file, your example is detected as Chinese: GB2312)

We would rather not like to do away with multi-encoding support for few strange cases. In that case, the reopening option sounds good.

My idea is to add `File -> Reopen With Encoding` submenu, and VS Code & Sublime have similar approach. Would you have any idea?

**Comment by dabroder** [comment]
I like `File -> Reopen With Encoding` submenu.
[Here](https://github.com/atom/encoding-selector/blob/master/lib/main.coffee) is the list used by Atom

**Comment by yhatt** [comment]
@dabroder Work done. I have implemented `File -> Reopen With Encoding` menu in #53.

![](https://cloud.githubusercontent.com/assets/3993388/17079167/ceb4a0ce-5142-11e6-909a-29e654c40c27.gif)

It would apply to the next release version (v0.0.9). I thank to your issue! :+1:
