### ISSUE TITLE
[Feature Request] Wanted Global Gaia Theme has a template theme of white background.

### ISSUE THREAD

**Issue by Keleir** [yhatt/marp#221]
I am fond of the theme of `Gaia`,  but when I insert a image with white background the template both `<!-- *template: invert -->` and `<!-- *template: default -->` seems not well. 
<img width="727" alt="2018-05-07 10 49 21" src="https://user-images.githubusercontent.com/7112075/39682872-e81d7f6e-51e4-11e8-86c5-a1fcfbc74c92.png">

<img width="745" alt="2018-05-07 10 46 33" src="https://user-images.githubusercontent.com/7112075/39682918-1927c15a-51e5-11e8-8ef0-b0bf684bd061.png">

I prefer that The `Gaia` theme has a template of white background like this `<!-- *template: white -->`        to meet such needs.

<img width="587" alt="2018-05-07 10 46 58" src="https://user-images.githubusercontent.com/7112075/39682926-281535c6-51e5-11e8-8c39-cc0f71d8092a.png">

**Comment by yhatt** [comment]
You can use inline style as a workaround.

```markdown
<!--
$theme: gaia
*template: white
-->

<style>
.slide_wrapper[data-template="white"] .slide {
  background: #fff !important;
}
</style>
```

In [Marp Next](https://github.com/marp-team/marp), we have `backgroundColor` directive to support changing background color directly (came from [Marpit framework](https://marpit.marp.app/directives?id=backgrounds)). The below example would receive the same result in future.

```markdown
<!-- _backgroundColor: white -->
```

> `_` works as same as `*` in current Marp.
