### ISSUE TITLE
Export as PDF from the command line

### ISSUE THREAD

**Issue by ssaunier** [yhatt/marp#222]
Hi there 👋 

First of all, marp is an amazing tool, can't wait to see [its reboot](https://github.com/marp-team/marp) released 🎉 !

This is more a feature request than a bug report. Would it be possible to add a feature to automatically export as a PDF a `.md` file using the relevant command line flags?

We can already a open a `.md` file with (on macOS):

```bash
/Applications/Marp.app/Contents/MacOS/Marp example.md
```

The API would look like something like this:

```bash
alias marp="/Applications/Marp.app/Contents/MacOS/Marp"

marp example.md --pdf # would produce example.pdf
marp example.md --pdf=output/other_name.pdf
```

Is this something planned?

Thank you!

**Comment by fabriciofx** [comment]
@yhatt WDYT? Is it hard to implement?

**Comment by deedubs** [comment]
I believe this will skip this pre-release version of Marp and be implemented directly in [marp-team/marp-cli](https://github.com/marp-team/marp-cli) if its not already!

**Comment by yhatt** [comment]
We have implemented PDF export in [@marp-team/marp-cli](https://github.com/marp-team/marp-cli) v0.0.4. :+1:
