### ISSUE TITLE
Bold font not rendered on Linux

### ISSUE THREAD

**Issue by Bronislas** [yhatt/marp#230]
Hi,

I'm using Marp both under Elementary OS and Windows.
I modified the default theme to use a custom font by adding at the beginning of the .md file :

```
.slide {
   font-family: Average Sans !important;
}
```

It works like a charm under Windows, but under Elementary OS, the bold texts put between asterisks (e.g. `**bold**` ) aren't rendered properly. If I add `font-weight: bold` to the css formating mentioned above, all the text is bold **except** the text put between asterisks.

If i use`<div style="font-weight: bold;">` instead of the asteriks, the text is bold as expected.

Sorry for my very bad english

**Comment by vinaykumar2491** [comment]
Doesnot work for me in latest marp-app for web..... 
Can you please tell me where to add the styles
