### ISSUE TITLE
Fail. 

### ISSUE THREAD

**Issue by brettswift** [yhatt/marp#233]
Install instructions don't contain any dependencies or setup. 

It just says download tar.   (done)

unzip  (done) 

run (booom) 💥 

`docker run --rm -it node bash`

then inside just to test: 

```
wget https://github.com/yhatt/marp/releases/download/v0.0.13/0.0.13-Marp-linux-x64.tar.gz
tar -zxf 0.0.13-Marp-linux-x64.tar.gz
./Marp
```
💥 💥 💥 
```
root@acacc8126b8b:/usr/local/bin/marp# ./Marp
./Marp: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

oh well.. onto try the next markdown presentation project.

**Comment by deedubs** [comment]
I think it's safe to assume that a GUI markdown tool for linux would require _more_ that what comes in the `node` docker container.

Why you thought you could run a GUI tool in a docker container without some pretty [exotic setup](https://blog.jessfraz.com/post/docker-containers-on-the-desktop#guis) is the real fail. Or as you put it :boom: :boom: :boom: 

I do agree that you should apologize for your unwarranted negativity or just go away though :stuck_out_tongue_winking_eye:

**Comment by yhatt** [comment]
Relax. :tea:
We would support Docker in [a CLI interface of the next Marp](https://github.com/marp-team/marp-cli) officially. 
https://hub.docker.com/r/marpteam/marp-cli/

Although it might work when we try harder, but currently we have no plan of GUI running on docker.
