### ISSUE TITLE
Auto-reloading

### ISSUE THREAD

**Issue by arximboldi** [yhatt/marp#234]
Hi!

I would like to use a different editor (`emacs`) to edit the text. It would be nice if Marp auto-reloaded the contents of the open-file if it changes externallyl such that I can use an external editor but visualize the changes as soon as I save.

Thanks for this cool project!

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. This issue is duplicated of #25 and #151.

And we have released a CLI tool that has supported watch mode in [Marp Next](https://github.com/marp-team/marp). See https://github.com/yhatt/marp/issues/25#issuecomment-427670640.
