### ISSUE TITLE
footers

### ISSUE THREAD

**Issue by willywutang** [yhatt/marp#238]
It would be great for Marp to support generation of footers in slides, such as page numbers, title strings, and insignia.

**Comment by Whadup** [comment]
I second this, I'd like to add a logos in the footer.

**Comment by yhatt** [comment]
Use [footer directive](https://github.com/yhatt/marp/blob/master/example.md#footer).

In next Marp at [@marp-team](https://github.com/marp-team), we are supporting inline imges in footer. Refer to [@marp-team/marpit](https://github.com/marp-team/marpit#styling-header-and-footer), our brand-new framework.
