### ISSUE TITLE
[Feature Request] Zoom in image with specifed scale

### ISSUE THREAD

**Issue by Keleir** [yhatt/marp#244]
I am using Marp mostly frequenctly. 
What makes me confused is that such cmd like `[80%](some.png)` can zoom out the image, 
but cmd like `[130%](some.png)`  will not zoom in the image.

I hope that will be effective. 🙏

**Comment by yhatt** [comment]
Actually the inline image can zoom-in now. I guess that is came from [the restriction to prevent sticking out from slide](https://github.com/yhatt/marp/blob/master/sass/themes/_slide.sass#L143-L144).

Currently, you can try this:

```
<style>
img {
  max-width: none !important;
}
</style>

![200%](image.png)
```
