### ISSUE TITLE
Marp” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by PavanPenjandra** [yhatt/marp#248]
When i installed in macos.I got the following message.Ima unable to run the Marp in macos
Marp” can’t be opened because it is from an unidentified developer.

**Comment by yhatt** [comment]
It's a restriction that come from a macOS security feature called Gatekeeper. You have to open context menu by `Control + Click` (or right click) and select "Open". Please refer: https://support.apple.com/en-us/HT202491

An essential issue is duplicated with #41.
