### ISSUE TITLE
Want the renew logo design for Marp Next

### ISSUE THREAD

**Issue by yhatt** [yhatt/marp#249]
I designed the Marp Next logo a year ago. It keeps the sharp "M" design and two blue colors from current Marp. By this logo, I wanted to represent the simplest way to *"write"* deck through Markdown.

<img src="https://raw.githubusercontent.com/yhatt/marp/master/images/marp.png" align="left" height="90" hspace="40" align="center" />
<img src="https://raw.githubusercontent.com/marp-team/marp/master/marp.png" align="right" height="100" hspace="40" align="center" />

&nbsp;\
▶️ 
<br clear="all" />

However, recently I found that Marp Next's logo is very similar to the logo of [Vue Material](https://github.com/vuematerial/vue-material). The shape and positional relation of two triangles is exactly same!

|[Marp Next](https://github.com/marp-team/marp)|[Vue Material](https://github.com/vuematerial/vue-material)|
|:---:|:---:|
|<img src="https://github.com/marp-team.png" width="200" />|<img src="https://github.com/vuematerial.png" width="200" />|

To avoid confusing, we think it might be necessary to change the logo of Marp Next. By reference to the current logo designs (below), please post your great new design if you have any ideas!

### The current Marp Next / Marpit (slide deck framework) logos

![marpit_logos](https://user-images.githubusercontent.com/3993388/47434779-40857600-d7de-11e8-8d19-61939ca847df.png)

### Logotype

Font of logotype are consisted by aligned lines, and arcs of completed circles.

![logotype](https://user-images.githubusercontent.com/3993388/47436010-9a873b00-d7e0-11e8-952f-19093f66cad3.png)

### Loading animation

<img src="https://rawcdn.githack.com/marp-team/marp-web/eb36bf46bcaf455f454a4c5ebb13cd27a3f20cf0/style/assets/marp-loading.svg" height="200" />

**Comment by yhatt** [comment]
I made two rounded versions based a current logo of Marp. They also have the heavy logotype.

<img width="503" alt="rounded-a" src="https://user-images.githubusercontent.com/3993388/49066561-d93b6580-f264-11e8-9a0e-10146fb86624.png">
<img width="503" alt="rounded-b" src="https://user-images.githubusercontent.com/3993388/49066562-d9d3fc00-f264-11e8-9a20-b166da377680.png">

**Comment by carolinetapp** [comment]
Woah! I designed this logo a couple of years ago and it looks VERY similar: 
![Asset 1](https://user-images.githubusercontent.com/53982484/62827087-2f470380-bb7d-11e9-859a-d319fd2c6ba0.png)
