### ISSUE TITLE
Support background changes to open files

### ISSUE THREAD

**Issue by zuckel** [yhatt/marp#25]
Marp should poll the file being edited and check for concurrent edits.
If a concurrent change by another application is detected, it should at least a dialog asking the user if the content should be reloaded from file.

This would facilitate usage of other editors which might be better for certain editing tasks, like block editing.

**Comment by yhatt** [comment]
Your approach is the right behavior as a text editor, and also would help to edit presentation by using another editor.

We would want to provide the best way. How about this?

- If a target file had edited by another process
  - and you had edited text on Marp's buffer (as you see titlebar's `*`),
    - It would ask by dialog whether reloading local file when you activated Marp.
  - If you hadn't,
    - Marp would reload file without your approval.
    - It means you can see the presentation preview of changing with your favorite editor. This behavior is similar to Deckset.

**Comment by zuckel** [comment]
Yes, please! This is the ideal behavior.
