### ISSUE TITLE
Support customize font-family

### ISSUE THREAD

**Issue by hoginwang** [yhatt/marp#250]
As the system setting, the default font family of Chinese character is a serif font. But a sans-serif font wuold be much better when you are writing header text.

Please support customize font-family!

![image](https://user-images.githubusercontent.com/4257672/47467608-df838f80-d829-11e8-9c61-27296731e143.png)

**Comment by yhatt** [comment]
Duplicated of #246. Already you can use `<style>` tag to customize CSS in markdown.

```markdown
<style>
.slide {
  font-family: 'Microsoft YaHei', 'SimHei', sans-serif !important;
}
</style>

# Render in sans-serif font
```

We recognize issues about font rendering in several languages especially CJK. We are going to support better CJK in Marp Next. To improve official themes, we want feedbacks about Chinese font rendering of [Marp Web](https://web.marp.app) / [Marp CLI](https://github.com/marp-team/marp-cli).
