### ISSUE TITLE
Image attributes suggestion

### ISSUE THREAD

**Issue by roipoussiere** [yhatt/marp#251]
I really like how Marp handles image size and position! :heart:

However these meta attributes could be even more powerful. Here is a suggestion for an eventual meta language, mainly based on the (already well used) [image magick geometry](https://imagemagick.org/script/command-line-processing.php#geometry) commands (which is, luckily, backward-compatible with the current behavior):

## size-related keywords

- `50%`: resize the image, in percents (current behavior);
- `30`: resize the image (keep aspect ratio, where 30 is the new width, in pixels);
- `30x20`: resize the image (keep aspect ratio, where 30 and 20 is the maximum width and height, in pixels, respectively);
- `30x20!`: resize the image (ignore aspect ratio, 30 and 20 is the actual new width and height, respectively);

## position-related keywords

- `+30-20`: add an offset, so the new image position will be 30px to the right and 20px to the top;
- `+30-20!`: set a new position using absolute coordinates, according to the top-left corner by default (negative numbers means that the image is positioned according to the opposite edge: in this case, the image is positioned 30px to the left edge and 20px to the bottom edge) ;
- `center`: center the image (current behavior);
- `right`: align to right (see also #37 ).

Of course, *size* and *position* can be combined, as the actual behavior of `50% center`, like `20x20 +30+20`.

**Comment by lapineige** [comment]
Would it be also possible to add a legend to the image ?
It's good to have precise positioning, but then it's tricky to add a text next to the image as a legend.

**Comment by roipoussiere** [comment]
@lapineige good idea!

Maybe an other tag *legend* could be fine, such as `[50% center legend: A rabbit](rabbit.png)`?

**Comment by yhatt** [comment]
Thanks for your suggestion :smile:

Currently we have already supported [image syntaxes based CSS declarations in brand-new Marpit framework](https://marpit.marp.app/image-syntax). But we could discuss about the best keyword to manipulate inline / background images.

|Suggestion|Marp|✨ [Marpit](https://marpit.marp.app/)|
|:---:|:---:|:---:|
|`50%`|`50%`|N/A *\*1*|
|`30`|N/A|`w:30`|
|`30x20`|N/A|N/A|
|`30x20!`|N/A|`w:30 h:20`|
|`+30-20`|N/A|N/A|
|`+30-20!`|N/A|N/A|
|`center`|`center`|N/A|
|`right`|N/A|N/A|

- *\*1*: Current Marp is using `zoom` style for resizing relative image size, but it cannot use in Firefox. [marp-web](https://github.com/marp-team/marp-web) requires supporting major browsers.

**Comment by yhatt** [comment]
> Maybe an other tag *legend* could be fine, such as `[50% center legend: A rabbit](rabbit.png)`?

I'm worried about mis-parsing in keywords. If we supported a legend, how about using `title` attribute of `<img>` tag? It is defined in the spec of Markdown.
https://spec.commonmark.org/0.28/#example-543

`![](image.jpg "legend")`

**Comment by roipoussiere** [comment]
Wow, you're doing a very good work with the next Marp, can't wait for the first release! 😅

The new image declaration is much better than current declaration! 👌

To be honest, I think that I personally prefer the light and efficient IM syntax, but if you like CSS-based keywords, what about implement:
- *margin* to define position, with `margin-left`, `margin-right`, etc. among with shortcuts `ml` and `mr`;
- `position:absolute`, with a shortcut `p:a`;
- and - icing on the cake - why not *padding* to define an eventual cropping, with `padding-left`/`pl`, `padding-right`/`pr`, etc. to respectively crop the left part and the right part of the image.
- `max-width` and `max-height` for a CSS equivalent of *30x20: resize the image (keep aspect ratio, where 30 and 20 is the maximum width and height, in pixels, respectively)*.

So your previous table becomes:

IM-base suggestion | CSS-based suggestion
---|---
`+30-20` | `ml: 30px mt: -20px`
`+30-20!` | `ml: 30px mt: -20px p:a`
`30x20` | `w:30 mh:20`

By the way, you are not going to implement *center* and *right* keywords? 🤔

**Comment by yhatt** [comment]
I think that we should collect more opinions about advanced image keywords. (RFC)

Currently Marpit has implemented the minimum operations expected to require by many users. Certainly I think IM based keywords are nice suggestion. In the other hand, I also think that it is not required for many user. We are learning from [Deckset](https://www.deckset.com/) that the beautiful deck is [not required too many operations](https://docs.decksetapp.com/English.lproj/Media/02-inline-images.html).

About `center` keyword, I could not decide to support because I think turning [inline element](https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements) `<img>` into [block element](https://github.com/yhatt/marp/blob/9229b73d3691b3b123d6906529d89c5017213ec9/sass/themes/_slide.sass#L147) implicitly is an unexpected behavior for user. Nevertheless if it is still valuable, we could reimplement `center` keyword.

**Comment by roipoussiere** [comment]
> In the other hand, I also think that it is not required for many user. We are learning from Deckset that the beautiful deck is not required too many operations.

UX-design is the art of allowing the user to use power tools without thinking about it. :) I mean that it's not a problem if 80% of users use only 20% of features, if these other features don't add complexity.

> Nevertheless if it is still valuable, we could reimplement center keyword.

I'm not sure to understand, you mean that the images will be centered automatically?
