### ISSUE TITLE
set image background color

### ISSUE THREAD

**Issue by roipoussiere** [yhatt/marp#252]
The very useful `![bg](path)` tag could be improved to support colors instead of images:

- `[bg](red)`: color keyword, among the [html colors list](https://www.w3schools.com/colors/colors_names.asp);
- `[bg](#39ffaf)`: color in hexadecimal representation.

**Comment by roipoussiere** [comment]
Found it!

```
<style>
.slide {
  background-image: url("fond.jpg") !important;
  background-size: cover;
}
</style>
```

**Comment by yhatt** [comment]
[Marpit framework](https://marpit.marp.app), the base framework of Marp Next, has implemented this feature! It would be available on [Marp Core](https://github.com/marp-team/marp-core) and [Marp CLI](https://github.com/marp-team/marp-cli) soon.

https://marpit.marp.app/image-syntax?id=background-color
