### ISSUE TITLE
This is fantastic! Do you accept donations?

### ISSUE THREAD

**Issue by teodorlu** [yhatt/marp#266]
Hello!

You just happened to save me a lot of time! I can't find any way to donate on the web site. Is that possible?

Teodor

**Comment by yhatt** [comment]
Sorry, I'm not ready to accept donation. 

There are some reasons, and an important point is that I'm living Japan. The personally transfer is prohibited by law, and I have no idea the correct way to recieve donation from user.

In additon, Marp is already towarding to [Marp Next](https://marp.app/) managed by @marp-team. Marp is supported by some OSS contributors, not only me. So donation to me is unfair for community.

**Comment by teodorlu** [comment]
Thanks for your reply. Regardless, I really appreciate the effort you and the other Marp contributors put in. I think you've found some kind of sweet spot for making simple, beautilful presentations. Keep up the good work!

Marp Next looks interesting, and seems like a good next step.

**Comment by yhatt** [comment]
**UPDATE**: I have stood in a line of [GitHub Sponsors](https://github.com/sponsors) to accept your donation. It would support payouts in Japan [according to a blog article](https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/#a-global-team). Please wait I get the sponsor!

**Comment by yhatt** [comment]
**UPDATE:** Started [Patreon](https://www.patreon.com/yhatt)! GitHub Sponsors think that would take a long time to accept small maintainer like me.

**Comment by teodorlu** [comment]
Hey!

I signed up for Patreon so I could support you a little. Since I was just interested in a one-time donation, I unsubscribed afterwards. Hope it helps!

Best regards, Teodor
