### ISSUE TITLE
Save Error Happened missing my work!

### ISSUE THREAD

**Issue by bobble1283** [yhatt/marp#270]
Few minutes ago, after I save and closed marp after editing, my file got empty !!!

I am seeking for the way to recover it .... Is it a bug ?? I am so disppointed.

![image](https://user-images.githubusercontent.com/21166787/58442440-ee168a00-811d-11e9-9e5f-46549d23d412.png)

**Comment by bobble1283** [comment]
I saw the annoucement that they will no more maintain this repository just now.
It may be my fault....

**Comment by yhatt** [comment]
Sorry for the inconvenience. yhatt/marp still have left for user having a slide deck with old Marp Markdown syntax. We no longer recommend to start using it for writing deck. (#267)

You should use more reliable editor and [Marp Next](https://github.com/marp-team/marp) integration: e.g. [VS Code + Marp extension](https://marketplace.visualstudio.com/items?itemName=marp-team.marp-vscode). Reinvention of the editor is not true work for us.
