### ISSUE TITLE
speaker notes in presentation mode

### ISSUE THREAD

**Issue by fabianmoronzirfas** [yhatt/marp#30]
As said in #13.  It would be great to have speaker notes for presentations

**Comment by grahamc** [comment]
One thing I found (probably a dirty secret) is you can embed HTML in to your slides. For my presentation, I've used the `aside` tag, and can disable it for presenting, while keeping the source open locally.

Like this:

```
<!-- $theme: default -->
<style>
aside {
	font-size: 12px;
    display: none;
}
</style>
---

# My Cool Slide

<aside>

 - foo
 - bar
 
</aside>
```

**Comment by will-hart** [comment]
I've found you can also do HTML style comments as a work around:

```html
<!-- this is a "speaker note" -->
```

**Comment by rtvb** [comment]
@will-hart You should add a reference to speaker notes through html comments in `example.md`.

**Comment by ebridges** [comment]
Currently Marp overloads HTML comments to use for Directives.  I'd suggest to be in line with other tools (e.g. [md2googleslides](https://github.com/googlesamples/md2googleslides) that Marp stick with HTML comments only for speaker notes, and use YAML front matter for directives.

**Comment by SuperV1234** [comment]
I've hacked in speaker note support in my fork (which also has presentation mode). PRs and improvements welcome. The notes are displayed in a separate window, so that the slides window can be fullscreen, 

![screenshot from 2017-10-21 11-28-29](https://user-images.githubusercontent.com/918661/31850893-0a9a577a-b653-11e7-8657-94dd873b4a8e.png)

https://github.com/SuperV1234/marp

**Comment by yhatt** [comment]
In marp-team/marpit#82, we are considering the format of presenter notes for Marp Next.

We would use HTML comments based on the discussion, but it has overloading to directives like he says in https://github.com/yhatt/marp/issues/30#issuecomment-289068871. We are planning to recognize comment as the presenter note only if its text had failed parse as an object YAML for Marp (Marpit) directives.

```markdown
# Directives

<!-- theme: gaia -->
<!-- class: invert -->

---

# Presenter notes

<!-- This is a presenter note for this page. -->
<!-- EXAMPLE: An EXAMPLE directive is not defined in Marp/Marpit, so this works as presenter notes. -->

---

# <!--fit--> Extra case on marp-core

`<!--fit-->` is not a presenter note. marp-core's comment for fitting header should also ignore.
```

In addition, we need to consider about whether implementing text formatting by inline markdown. At first release, we would support only plain text. But formatting like [md2googleslides](https://github.com/gsuitedevs/md2googleslides#speaker-notes) might be valuable.

**Comment by yhatt** [comment]
Marpit framework (The base framework for Marp Next tools) can [parse HTML comments](https://marpit.marp.app/usage?id=presenter-notes). So community-driven tools can use collected comments as presenter note.

[marp-vue-slide](https://github.com/yhatt/marp-vue-slide) is a practical example.

[![presenter-notes](https://user-images.githubusercontent.com/3993388/61180823-d48eba80-a657-11e9-9c89-47c121f75351.png)](https://github.com/yhatt/marp-vue-slide)


In addition, Marp Next's [PPTX conversion](https://github.com/marp-team/marp-cli#convert-to-powerpoint-document---pptx) is available the support of conversion speaker notes written in HTML comment.
