### ISSUE TITLE
Support of auto line break on syntax highlighting

### ISSUE THREAD

**Issue by bells17** [yhatt/marp#33]
Now not be a new line at the time of the syntax highlighting.

example: 

<img width="1219" alt="_untitled___" src="https://cloud.githubusercontent.com/assets/2158863/16867006/41cf8f78-4aaa-11e6-9784-b89e4a68b14e.png">

When a character does not fit on the screen,
I think that it should be a new line in the automatic.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues.

Auto line break might break source code. In [the core](https://github.com/marp-team/marp-core) of [Marp Next](https://github.com/marp-team/marp), we have supported [auto scaling of code block](https://github.com/marp-team/marp-core#code-block-only-for-default-and-gaia-theme) in several themes (marp-team/marp-core#23). This behavior also has a compatibillity with the other app. (e.g. [Deckset](https://docs.decksetapp.com/English.lproj/Formatting/06-code-blocks.html#automatic-scaling))
