### ISSUE TITLE
broken img tag with relative path.

### ISSUE THREAD

**Issue by sudoyu** [yhatt/marp#34]
I'm using document directory outside of marp binaries.

```
![](images/my.png)
```
it works.

```
<img src="images/my.png" />
```
doesn't work.

when use full absolute path, img tag works.

**Comment by include** [comment]
same problem here.

**Comment by yhatt** [comment]
Thanks. Marp has implemented logic to resolve the relative image path written by Markdown, but `<img>` tag has not.

However, we didn't need have logic to resolve if I had known the best way which use HTML's `<base>` tag. I'm going to try to fix it.

**Comment by yhatt** [comment]
@sudoyu @include Done in #49! We fixed resolving relative path.

![](https://cloud.githubusercontent.com/assets/3993388/17046461/ad258ba6-500e-11e6-8b1b-5ca7a3ec8274.png)

It would apply to next version `v0.0.9`. We are grateful to your report.
