### ISSUE TITLE
Text encoding problems

### ISSUE THREAD

**Issue by afiller** [yhatt/marp#35]
Hello I found a bug in 0.0.8:

When storing a file containing Emojis they are not stored/loaded correctly: 😊👍 ends up in two cryptic letters when loading the file again.

Since the editor is able to handle full UTF-8 I would suggest to simply adjust the saving/loading methods to handle UTF-8 correctly.

I tested it on OS X (now called macOS) ;-)

Great project!!! Looking forward to updates.

Andreas

**Comment by dabroder** [comment]
Same issue: https://github.com/yhatt/marp/issues/22

**Comment by afiller** [comment]
Can be, right. I will close this here. I reported a way to fix the problem in the other issue.
