### ISSUE TITLE
Cyrillic is behaving strangely in editor

### ISSUE THREAD

**Issue by Ivan-Istomin** [yhatt/marp#39]
![untitled 2016-07-17 16-05-43](https://cloud.githubusercontent.com/assets/5376495/16900800/5df72b36-4c38-11e6-9dce-9fde995074cb.png)

**Comment by yhatt** [comment]
I'm sorry for that I can't understand Cyrillic and the background of its environment.
Actually font rendering localized for multi-byte language (CJK). So Cyrillic renders by fullwidth, because of the complex background. [Reference (in Japanese)](http://mplus-fonts.osdn.jp/cgi-bin/blosxom.cgi/mplus_fonts/mplus_fonts-080821-2.html)

At present, I have no any idea to improve font settings for globalizing.

**Comment by Ivan-Istomin** [comment]
I remember there was same problem with Brackets. It was solved by simply replacing the font supports Cyrillic.

**Comment by vovkkk** [comment]
On Windows it is even worse.

![2016-08-11_21-03-16](https://cloud.githubusercontent.com/assets/1975298/17591151/0b83d376-6007-11e6-8f43-103f9a3d2cb1.png)

There is [article](http://www.artlebedev.ru/kovodstvo/sections/183/) in Russian on this issue, which recommends [Noto font](http://www.google.com/get/noto/).
I’d prefer Consolas though.

**Comment by will-hart** [comment]
Sounds like this could be fixed by #5 or #1?

**Comment by Ivan-Istomin** [comment]
@will-hart yes!

**Comment by will-hart** [comment]
A work around for these issues is to include a slide like the following:

```
---

<style type="text/css">
	html, body, div, p { font-family: 'Wingdings' }
</style>

```

I do this on a separate slide right at the end because including the style tag seems to mess up heading only formatting.  You may want to use a different font though :)

**Comment by Ivan-Istomin** [comment]
@will-hart my mistake, sorry, the solution is to change the font for the editor, not for slide. As you can see on screenshots.

**Comment by will-hart** [comment]
Ah yes, oops :)

**Comment by yhatt** [comment]
I changed the default font for the editor in #93 (system default monospace). You can use by editing `config.json` if you have any font. This change would apply in v0.0.9. I'll close this issue.
