### ISSUE TITLE
Feature Request: markdown view pdf export

### ISSUE THREAD

**Issue by noullove** [yhatt/marp#4]
Thank you for making a good program.

Please allow output to the screen that displays the mark-down view as a PDF. (not slide view)

**Comment by yhatt** [comment]
Thanks issue! :+1:

Though I'm thinking that Marp's slide features are more important than Markdown, It's worth working if you need.

Someday I want to add exporting Markdown as PDF. Until then, you can use the other useful editors. (e.g. [markdown-pdf](https://atom.io/packages/markdown-pdf) on [Atom](https://atom.io/))
