### ISSUE TITLE
Feature Request: Vim style key-binding

### ISSUE THREAD

**Issue by juhoi** [yhatt/marp#43]
It would be better if I could use Vim style key-binding.

**Comment by ErichDonGubler** [comment]
It seems like this would be a serious scope creep if the editor itself got changed -- implementing this functionality doesn't seem easy, and not something that @yhatt might want to maintain. I DO have a suggestion to resolve your problem, though.

In editors like Sublime Text, changes to files are normally automatically detected, and the file is reloaded automatically when the user refocuses the app. What if Marp did that, and you could use something like `vim` in your terminal or even `gvim`? The flow would be like this:

1. Put Marp into Presentation mode (just show the rendered slide)
2. Split Marp and your preferred editor (in this case, `vim`) on your screen
3. Focus on `vim`, make changes, write the file buffer
4. Refocus Marp, and the file changes for you. Voila!

Thoughts?

**Comment by yhatt** [comment]
I agree with @ErichDonGubler's. I can understand thing that many user hope to write presentation like with any favorite editor, but I want to avoid bringing a scope creep.

Would you like to edit presentation by using your vim if Marp were implemented #25?

**Comment by juhoi** [comment]
@ErichDonGubler , @yhatt : Thank you! I will try that.
