### ISSUE TITLE
Backslashes render incorrectly in the CodeMirror editor

### ISSUE THREAD

**Issue by will-hart** [yhatt/marp#46]
As discussed in #45, when I type a backslash `\` in the editor it appears as a &yen; symbol - see the attached screenshot. This happens in the 0.0.8 binaries as well as the branch in the pull request. 

![backslash](https://cloud.githubusercontent.com/assets/391950/17021089/ce1698f4-4f88-11e6-9382-b9787a638498.png)

On the top left is the **&yen;** symbol that appears, on the right is the rendered markdown slide showing the backslash correctly displayed. The file at the bottom shows the backslash is correctly saved to file.

**Comment by yhatt** [comment]
Hmm, Perhaps this cause would be a side effect for supporting CJK. It is the same as #39.
https://en.wikipedia.org/wiki/Backslash#Confusion_in_usage

**Comment by yhatt** [comment]
I'll close this issue by merging #93. See also: #39.
