### ISSUE TITLE
Request: Marp for documents?

### ISSUE THREAD

**Issue by candlerb** [yhatt/marp#48]
Marp is absolutely fantastic for slides. I was wondering, how hard would it be to modify Marp so that it could be used as a markdown document editor? Or do you know of a similar project that already exists?

I would like to be able to open and edit markdown documents, preview them live (as Marp does), export as PDF, and export as HTML - either converted to plain HTML, or linking to some Javascript to render within a browser.

The application is for editing classroom worksheets like [this one](https://nsrc.org/workshops/2016/rwnog-nmm/netmgmt/en/smokeping/exercises-smokeping-part1.htm)

Currently we do this by editing the markdown in a text editor and then running it through pandoc. But this workflow does not give any live visual feedback from the editing process. It also requires pandoc to be installed where you are editing; and each time you make a change you have to re-run it and refresh in your browser to see what the rendered output looks like.

I think that unless you generate your rendered output from the same tool you are editing with, there's a risk that what you see is *not* what you get in the final output.

Hence a tool like Marp which both renders while editing *and* generates the final output is of great interest.

**Comment by Emkaytoo** [comment]
There are a bunch of Markdown editors with live preview available. If you're on a Mac platform, then I'd recommend [Mou](http://25.io/mou/) or [Macdown](http://macdown.uranusjr.com/) (which is based on Mou and is open source), as I believe both have live preview and export as PDF/HTML. Mou has stylesheet support built into it, too. 

I'm not familiar with Windows editors, but there are several cross-platform [Electron apps](http://electron.atom.io/apps/) that can edit markdown.

**Comment by will-hart** [comment]
There are also tons here https://github.com/sindresorhus/awesome-electron#apps. Most are some variation on CodeMirror editor + preview pane.

**Comment by candlerb** [comment]
Thank you for your replies - I will investigate these options.

I am looking for (a) cross-platform, (b) can convert Markdown to HTML as well as edit Markdown, (c) scriptable (i.e. invoke from command line) for Markdown to HTML conversion.
