### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by tforgione** [yhatt/marp#50]
Hi everyone,

a friend told me about this project, and it seems really, really cool.

However, I am used to my custom editor, and I was wondering if there was a possibility to use this to generate pdf with a command line. 

Is it already done ? Is it something you are intersted in ? And, maybe, can I help ?

**Comment by yhatt** [comment]
We're sorry. Currently Marp is lacking of supporting to edit with custom editor. Therefore it can't generate PDF by command line.

However we have understood these needs. (Similar needs: #25)

**Comment by grahamc** [comment]
While #25 is sort of similar, I think what @tforgione is really going for is the ability to use it in a build tool, like `./Marp --input-presentation=./slides.md --output=slides.pdf`. This is definitely a feature I'm interested in.

**Comment by grahamc** [comment]
PS: Thank you so much for your efforts on Marp, it is already a lovely experienc. :)

**Comment by tforgione** [comment]
> I think what @tforgione is really going for is the ability to use it in a build tool, like `./Marp --input-presentation=./slides.md --output=slides.pdf`

Yes, sorry I wasn't clear, but this is totally what I meant. If it's possible, then anyone could use it with any text editor and simply run this command to generate the pdf. 

I tried to look at the sources because it seemed to me that it would be easy to do, but I think I was wrong, I don't really know coffescript and electron... maybe it's possible to complete the pipeline without showing the window ?

**Comment by colindean** [comment]
Found this while looking to see if anyone had used Marp in a CI system. I'd love to be able to version my presentations and have CI build them for me, e.g. push commits to a Github repo, and on tagged commits, the presentation is built by Travis and uploaded to Github Releases. Marp does a stellar job of rendering and I'd love to use it in this way.

**Comment by morph027** [comment]
Same here, auto CI building PDFs would be great! ;)

**Comment by radare** [comment]
Check out ssg for this https://github.com/jroimartin/ssg

**Comment by lemire** [comment]
@radare I don't think that ``ssg`` will work unless the author commits to supporting ``marp`` specifically. For example, will mathematical formulas work?

**Comment by radare** [comment]
nope, ssg doesnt supports this, but i was just proposing to checkout ssg to see how to generate postscript from markdown :) also, a subset would be good too, i have never used a mathematical formula in markdown

**Comment by Naereen** [comment]
Hi,
Any update on this feature request?
@yhatt would it be hard to do?

**Comment by stilvoid** [comment]
+1 This would be incredibly useful. More useful than the editor, to be honest :)

**Comment by Naereen** [comment]
@stilvoid I wouldn't be so strict about that, but I agree.

**Comment by xukai92** [comment]
So I was trying to do the same but ended up just using `pandoc` to do the conversion.

**Comment by yhatt** [comment]
We have released CLI interface on [@marp-team/marp-cli](https://github.com/marp-team/marp-cli), that is [the family of Marp Next](https://github.com/marp-team/marp). The latest version v0.0.4 can export PDF :+1:

**Comment by tforgione** [comment]
Thank you for the hard work.

@marp-team/marp-cli is exactly what I was hoping for. You can be sure I'll use it!
