### ISSUE TITLE
Feature request: support Incremental Slides syntax

### ISSUE THREAD

**Issue by die4live** [yhatt/marp#55]
ref to: [remark Wiki](https://github.com/gnab/remark/wiki/Markdown), `--` is used to make a slide increment to previous one.

BTW, the `???` syntax to add presentation notes is also a good idea. As remark.js has already been the best solution to convert markdown to html slides by now.

**Comment by niklas-dahl** [comment]
any updates on this feature?

**Comment by yhatt** [comment]
Currently we not have update about this. We might be careful for adding syntax because it is against #83.

**Comment by yhatt** [comment]
UPDATE: A brand-new Marp Next tools (#267) has adopted #89 in favor of CommonMark compatible syntax, not remark style syntax.
https://marpit.marp.app/fragmented-list
