### ISSUE TITLE
Chocolatey

### ISSUE THREAD

**Issue by ygorlazaro** [yhatt/marp#6]
Nice project, I'm already using to post at my blog (hosted with Ghost CMS).

I think it's a good idea publish the project a Chocolatey, to easy install/updates at client side. Can we work with it?

**Comment by yhatt** [comment]
Thanks. Actually I didn't know [Chocolatey](https://chocolatey.org/)..

We are aiming that Marp can use easily by anyone (= not only superuser). So I thought to implement Auto-update by Electron's [`autoUpdater`](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md) and we have no plan to support Chocolately at the moment.

However, the `autoUpdater` in Windows requires to install by installer created for Electron. I understand it may cause painful to you.

I'm sorry to have no knowledge of Chocolately, but we'll welcome to add it (like a ArchLinux's AUR: https://aur.archlinux.org/packages/marp/).

**Comment by ygorlazaro** [comment]
Well, understood. I'll send the last release package to Chocolatey's servers, but I don't know if it will be able to install in a non-admin account. This is something I will need to test.

Do you think this only worths if Marp can be installed by a normal user?

**Comment by yhatt** [comment]
Of course.
Current version of Marp can run as normal user without install. So, it would not lose its experiences even if installed as normal user.

Providing management by Chocolatey would make its user happy in while Marp has no installer.

**Comment by majkinetor** [comment]
I will do this: https://github.com/majkinetor/au-packages/issues/82
