### ISSUE TITLE
gaia.css reffer internet resources

### ISSUE THREAD

**Issue by yasumichi** [yhatt/marp#66]
gaia.css reffer internet resources as bellow.

``` css
@import url(https://fonts.googleapis.com/css?family=Lato:400,900);
@import url(https://fonts.googleapis.com/css?family=Roboto+Mono:400,700);
```

As a result, it takes time to generate the preview on enviroment can't connect internet.

**Comment by Naereen** [comment]
Any change of merging #106 and fixing #66 ?
