### ISSUE TITLE
Feature Request: Math typesetting support

### ISSUE THREAD

**Issue by apetresc** [yhatt/marp#7]
Would love to use this for talks/presentations that involve mathematics, without having to pre-render formulas and inject them as images.

I think the easiest way to accomplish them is by using [MathJax](https://www.mathjax.org/), and having the Markdown processor emit it. Luckily, there appears to be a Markdown-it plugin for MathJax on npm: https://www.npmjs.com/package/markdown-it-mathjax

I think this should work fairly easily: just add this plugin and inject the MathJax JS on the rendered page.

**Comment by apetresc** [comment]
@dextorious: Makes sense, good suggestion. I've edited the name of the issue to reflect that *any* math typesetting system would be great :)

**Comment by koaning** [comment]
I accenditally opened up an issue with the same topic. Will make the reference and close it.

**Comment by yhatt** [comment]
Thanks for discuss. I'm recognizing that the math syntax is missing compared with other Markdown editors and Deckset.

Lucky again, we can also find a markdown-it plugin for KaTeX: [waylonflinn/markdown-it-katex](https://github.com/waylonflinn/markdown-it-katex)

**Comment by will-hart** [comment]
I've got this working with KaTeX, I'll submit a PR shortly if you would like?

**Comment by yhatt** [comment]
Oh, Thanks. I'd love to see your implemented. 😍

I think it is the best (at the moment) to make new `slide.sass` which included KaTeX CSS by Sass precompiling, in the same as including GitHub CSS to current theme sass file.

**Comment by will-hart** [comment]
Ok, I'll have a look at doing it that way

**Comment by yhatt** [comment]
I must thank for @will-hart's contribution. We have merged his implemention of KaTeX rendering into `master`.

![screenshot](https://cloud.githubusercontent.com/assets/3993388/17055991/68343c44-504b-11e6-920f-209fe3346477.png)

We would be able to ship v0.0.9 that has math typesetting, ahead of planned milestones schedule!
