### ISSUE TITLE
Umlauts (and in-line UTF emoji) aren't loaded from files

### ISSUE THREAD

**Issue by DivineDominion** [yhatt/marp#73]
Marp's editor works fine for this and the resulting .md file looks good in my text editor. When Marp opens the file again, though, ÜÄÖ etc. are replaced with typical fragmented characters when you use the wrong encoding.

**Comment by will-hart** [comment]
Is this addressed by #53?

**Comment by DivineDominion** [comment]
It seems so! Will check when the next release is out.
