### ISSUE TITLE
Relative images links stop working

### ISSUE THREAD

**Issue by japgolly** [yhatt/marp#79]
The first time I used Marp and created a file I could put images in the same directory as the `.md` and reference them without a path.

Unfortunately, after I moved the directory the images stopped working and now need a full path to load.
I even logged into my machine with a different user account and still couldn't load relative images anymore. Does record the current-working-directory once, save it _globally_, and never update it again? That sounds bizzarre but it that's how Mark is behaving on my machine.

**Comment by dhanifudin** [comment]
you can check from [example.md](https://raw.githubusercontent.com/yhatt/marp/master/example.md) how to load from relative image

```markdown
# ![](images/marp.png)
```

**Comment by japgolly** [comment]
@dhanifudin I don't think you really read my issue description properly.

**Comment by yhatt** [comment]
You have put image to same directory of marp binary. And the other `.md` file on different directory couldn't load it, right?

I enhanced relative path support in #49. But I had not consider commonly used image. You must use absolute path if you use it.

[Atom](https://atom.io/), the typical Electron app, resolved this issue by defining custom URI scheme: `atom://` (redirect to `~/.atom/`). If Marp were implemented redirect path from `marp://image.png` to `$MARP_INSTALLED_FOLDER/image.png`, would it help you? (It's just an idea...)

**Comment by japgolly** [comment]
> You have put image to same directory of marp binary. And the other .md file on different directory couldn't load it, right?

No, I always put image and `.md` in the same directory. I never use the Marp binary directory.

Maybe this is clearer:

##### Step 1: Create for first time
```
# Files
~/first-time/example.md
~/first-time/example.png
```
Open `example.md` in Marp. Image displays correctly.

##### Step 2: Move directory
```
mv ~/first-time ~/renamed

# Files
~/renamed/example.md
~/renamed/example.png
```
Open `example.md` in Marp. Image does *not* display correctly.
