### ISSUE TITLE
Support for task list markup

### ISSUE THREAD

**Issue by tributeToInsanity** [yhatt/marp#80]
It says the ext format is based on Github Flavored Markdown but when adding the markup for a task list, it will not be rendered in Marp:

```
tasks lists example:

- [x] This is a complete item
- [ ] This is an incomplete item
```

Is this feature not supported or am I missing something in the markup/format?

![marp](https://cloud.githubusercontent.com/assets/20978258/17903214/9d0e10ce-6938-11e6-905c-c78f60f6c187.PNG)

**Comment by will-hart** [comment]
Workaround using emjoi

    - :white_check_mark: checked
    - :white_large_square: white unchecked
    - :black_large_square: black unchecked

**Comment by yhatt** [comment]
Currently it's easy to render by using [markdown-it-task-list](https://github.com/revin/markdown-it-task-lists) but it has technical difficulty to sync states.

**Comment by garnierclement** [comment]
Other workaround using HTML codes for Unicode characters &#9744; and &#9745; 
![capture d ecran 2016-11-13 a 15 54 03](https://cloud.githubusercontent.com/assets/1900136/20246578/b18a8570-a9b9-11e6-9920-b24272eb4625.png)

```
&#9744; unchecked box
&#9745; checked box
```

**Comment by cybertaf** [comment]
Most of them works : 
[emoji-cheat-sheet](http://www.webpagefx.com/tools/emoji-cheat-sheet/)

**Comment by Naereen** [comment]
The goal is not to use emojis or HTML characters, it's to support one more (unofficial) Markdown feature right out-of-the-box.
