### ISSUE TITLE
How to disable automatic syntax highlighting in blocks of code?

### ISSUE THREAD

**Issue by 0mp** [yhatt/marp#81]
From what I understand, highlight.js working underneath Marp does automatic syntax highlighting.  I am also able to specify my desired syntax color scheme manually. I am not sure how I can disable any syntax highlighting in a code block.

**Comment by will-hart** [comment]
Does specifying language as `text` help?

![capture](https://cloud.githubusercontent.com/assets/391950/17918774/39efd094-6a0b-11e6-8881-10386d2f79ba.PNG)

**Comment by 0mp** [comment]
It's perfect! Thanks a lot! Where did you find it?

**Comment by will-hart** [comment]
It's the standard way to set the language for markdown code blocks and text
blocks are unformatted
