### ISSUE TITLE
Implicit use of Japanese fonts should be avoided in sass files, or Chinese characters will display improperly

### ISSUE THREAD

**Issue by vhyme** [yhatt/marp#85]
...And to be more internationalized, I suggest the project use system default fonts or allow users to customize fonts for the editor and the presentation.

**Comment by yhatt** [comment]
Marp have some problems by specified to Japanese (as you pointed). So I added this issue to v0.0.9 milestone.

The font customizability for editor have implemented by #75 (But have not UI).
For theme, we would use international font (e.g. system based font) in default and Gaia theme. (It means to lose backward compatibility of rendering)

**Comment by yhatt** [comment]
I want to discuss about the default `font-family` of editor.
https://github.com/yhatt/marp/pull/93#discussion_r81475623
