### ISSUE TITLE
Unicode characters interpreted as ASCII when reading file

### ISSUE THREAD

**Issue by gerbend** [yhatt/marp#86]
When I insert a Euro symbol (€), it is displayed correctly. After saving and then reopening the markdown document, the unicode symbol is displayed as three separate ASCII symbols in both the text editor and the preview.

€ (unicode 0xE282AC) is replaced by â‚¬ (ascii 0xE2, 0x2A and 0xAC)

**Comment by will-hart** [comment]
Have you tried from the master branch? Various encoding issues were fixed there but have not been put into a release.

**Comment by bastengao** [comment]
I have a same issue.

**Comment by yhatt** [comment]
The encoding misdetection caused by [jschardet](https://github.com/aadsm/jschardet) had already reported on #22, #59 and #73. And they would be supported temporary by #53.

**Comment by koliyo** [comment]
Seems to still be an issue. I had to "Reopen with encoding - UTF-8"  to get proper rendering
