### ISSUE TITLE
Feature Request: Reveal bullet points one-by-one

### ISSUE THREAD

**Issue by japgolly** [yhatt/marp#89]
It would be super useful to have a list of points in markdown that reveal each new point in a new slide.

Example: This source

``` md
* ABC
* DEF
* XYZ
```

could generate three slides:
##### 1.

```
* ABC


```
##### 2.

```
* ABC
* DEF

```
##### 3.

```
* ABC
* DEF
* XYZ
```

**Comment by yhatt** [comment]
If Marp were implemented incremental slides as same as [remark](https://github.com/gnab/remark) style ( https://github.com/gnab/remark/wiki/Markdown#incremental-slides ), would it you help?

See: #55

**Comment by japgolly** [comment]
Yes, that would be good. I didn't realise this was called "incremental slides" and I think we can actually close this as a duplicate of #55.

**Comment by yhatt** [comment]
OK. We close this issue. You can dicuss in #55 if you want.

**Comment by yhatt** [comment]
UPDATE: A brand-new Marp Next tools (#267) has adopted a way reported in this issue in favor of CommonMark compatible syntax, not remark style syntax.

We can get expected behavior by using [Marp CLI](https://github.com/marp-team/marp-cli) v0.8.0 with HTML export.
